language: python
sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"

addons:
  apt:
    packages:
      - libhdf5-serial-dev

cache:
  apt: true
  directories:
    - $HOME/.cache/pip

install:
  - pip install --upgrade pyflakes

before_script:
  # static code analysis
  #   pyflakes: mainly warnings, unused code, etc.
  - python -m pyflakes openpmd_updater

script:
  # execute actual scripts
  - python setup.py install
  - nosetests

  # Test the CLI and validate with the updater
  - git clone https://github.com/openPMD/openPMD-validator.git
  - cd openPMD-validator ; python setup.py develop
  # Create an openPMD 1.0.0 file
  - openPMD_createExamples_h5
  # Update it
  - openPMD_updater_h5 -i example.h5
  # Validate as an openPMD 2.0 file
  - git checkout 2.0.X ; openPMD_check_h5 -i example.h5 --EDPIC
